### Imputation con rete neurale (una feature alla volta)

In [160]:
import pandas as pd
import imputation as imp 
import models 

dataset = pd.read_csv('/home/biso/Tirocinio/tirocinio/Imputation/datiLussazioniDefinitivi.csv', delimiter=';')
dataset

,CASE_ID,BREED,GENDER_01,AGEATSURGERYmo,BODYWEIGHTKG,Taglia,BCS,INDICATIONFORTHR,HIPRL,YEAR,...,NECKSIZE,HEADSIZE,ALO,CUPRETROVERSION,STEMANTEVERSIONREAL,RECTUSFEMORISM.RELEASE,first_lux_days_after_thr,DIRECTION,LUX_01,LUX_CR
0,1,3,0,"56,5","31,6",1,5,4,R,2021,...,4,1,46.0,15,"17,7",NO,NaN,NaN,0,0
1,2,8,0,"9,4","40,9",1,5,4,L,2021,...,5,1,40.0,25,"27,7",NO,NaN,NaN,0,0
2,3,10,0,"15,1333333333333",35,1,5,4,R,2021,...,4,1,42.0,20,"27,7",YES,NaN,NaN,0,0
3,4,6,0,"83,4333333333333","18,7",0,6,4,L,2021,...,4,0,40.0,18,"24,2",NO,NaN,NaN,0,0
4,5,5,0,"7,53333333333333","36,4",1,4,4,L,2021,...,5,1,42.0,28,"25,9",YES,NaN,NaN,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3192,3193,3,0,"57,4333333333333",25,1,5,2,R,2010,...,3,0,43.0,32,"27,7",NO,35.0,CRANIO-DORSALE,1,1
3193,3194,5,1,"49,2333333333333",38,1,6,2,R,2009,...,4,0,48.0,26,"25,9",NO,18.0,CRANIO-DORSALE,1,1
3194,3195,13,0,"38,0333333333333",43,1,5,2,R,2008,...,4,0,48.0,4,"11,5",NO,30.0,CRANIO-DORSALE,1,1
3195,3196,5,1,"11,5333333333333",28,1,5,2,R,2001,...,4,0,52.0,10,"31,3",NO,26.0,CRANIO-DORSALE,1,1
3196,3197,3,0,"9,53",36,1,5,2,L,2020,...,4,1,43.0,35,"17,7",NO,83.0,CRANIO-DORSALE,1,1

In [161]:
dataset = imp.clean_dataset(dataset)

dataset['DIRECTION'] = dataset['DIRECTION'].replace('CRANIO-DORSALE', 0)
dataset['DIRECTION'] = dataset['DIRECTION'].replace('CAUDO-VENTRALE', 1)

cols = ['n_luxation', 'first_lux_days_after_thr', 'DIRECTION']
dataset[cols] = dataset[cols].fillna(-1)

In [162]:
dataset.isna().sum()

CASE_ID                     0
BREED                       0
GENDER_01                   0
AGEATSURGERYmo              0
BODYWEIGHTKG                0
Taglia                      0
BCS                         2
INDICATIONFORTHR            0
HIPRL                       1
YEAR                        0
n_luxation                  0
GENERATION                  0
STEMSIZE                    0
CUPSIZE                     0
NECKSIZE                    0
HEADSIZE                    0
ALO                         1
CUPRETROVERSION             0
STEMANTEVERSIONREAL         1
RECTUSFEMORISM.RELEASE      0
first_lux_days_after_thr    0
DIRECTION                   0
LUX_01                      0
LUX_CR                      0
dtype: int64

In [163]:
dataset.head()

,CASE_ID,BREED,GENDER_01,AGEATSURGERYmo,BODYWEIGHTKG,Taglia,BCS,INDICATIONFORTHR,HIPRL,YEAR,...,NECKSIZE,HEADSIZE,ALO,CUPRETROVERSION,STEMANTEVERSIONREAL,RECTUSFEMORISM.RELEASE,first_lux_days_after_thr,DIRECTION,LUX_01,LUX_CR
0,1,3,0,56.500000,31.6,1,5.0,4,1.0,2021,...,4,1,46.0,15,17.7,0,-1.0,-1.0,0,0
1,2,8,0,9.400000,40.9,1,5.0,4,0.0,2021,...,5,1,40.0,25,27.7,0,-1.0,-1.0,0,0
2,3,10,0,15.133333,35.0,1,5.0,4,1.0,2021,...,4,1,42.0,20,27.7,1,-1.0,-1.0,0,0
3,4,6,0,83.433333,18.7,0,6.0,4,0.0,2021,...,4,0,40.0,18,24.2,0,-1.0,-1.0,0,0
4,5,5,0,7.533333,36.4,1,4.0,4,0.0,2021,...,5,1,42.0,28,25.9,1,-1.0,-1.0,0,0

In [164]:
dataset

,CASE_ID,BREED,GENDER_01,AGEATSURGERYmo,BODYWEIGHTKG,Taglia,BCS,INDICATIONFORTHR,HIPRL,YEAR,...,NECKSIZE,HEADSIZE,ALO,CUPRETROVERSION,STEMANTEVERSIONREAL,RECTUSFEMORISM.RELEASE,first_lux_days_after_thr,DIRECTION,LUX_01,LUX_CR
0,1,3,0,56.500000,31.6,1,5.0,4,1.0,2021,...,4,1,46.0,15,17.7,0,-1.0,-1.0,0,0
1,2,8,0,9.400000,40.9,1,5.0,4,0.0,2021,...,5,1,40.0,25,27.7,0,-1.0,-1.0,0,0
2,3,10,0,15.133333,35.0,1,5.0,4,1.0,2021,...,4,1,42.0,20,27.7,1,-1.0,-1.0,0,0
3,4,6,0,83.433333,18.7,0,6.0,4,0.0,2021,...,4,0,40.0,18,24.2,0,-1.0,-1.0,0,0
4,5,5,0,7.533333,36.4,1,4.0,4,0.0,2021,...,5,1,42.0,28,25.9,1,-1.0,-1.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3192,3193,3,0,57.433333,25.0,1,5.0,2,1.0,2010,...,3,0,43.0,32,27.7,0,35.0,0.0,1,1
3193,3194,5,1,49.233333,38.0,1,6.0,2,1.0,2009,...,4,0,48.0,26,25.9,0,18.0,0.0,1,1
3194,3195,13,0,38.033333,43.0,1,5.0,2,1.0,2008,...,4,0,48.0,4,11.5,0,30.0,0.0,1,1
3195,3196,5,1,11.533333,28.0,1,5.0,2,1.0,2001,...,4,0,52.0,10,31.3,0,26.0,0.0,1,1
3196,3197,3,0,9.530000,36.0,1,5.0,2,0.0,2020,...,4,1,43.0,35,17.7,0,83.0,0.0,1,1

In [165]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import Adam


# Creazione del modello di rete neurale
def build_model_linear(input_dim, n):
    model = Sequential([
        # primo strato che prende in input il numero di feature del dataset, il numero di neuroni, la funzione di attivazione ReLU
        Dense(10, activation='relu', input_dim=input_dim),      

        # strato di dropout, che disattiva casualmente un numero di neuroni durante ogni passaggio di addestramento per prevenire overfitting
        Dropout(0.2),                                           

        # strato che prende in input il numero di neuroni e la funzione di attivazione ReLU
        Dense(5, activation='relu'),

        # strato di dropout
        Dropout(0.2),

        # strato finale con un singolo neurone e una funzione di attivazione lineare
        Dense(n, activation='linear')  # Predice una singola feature
    ])

    # compilazione del modello in cui si specifica la funzione di perdita (MSE) e si utilizza come ottimizzatore Adam
    model.compile(loss='mse', optimizer='adam')
    return model

# Creazione del modello di rete neurale
def build_model_sigmoid(input_dim, num_classes):
    model = Sequential([
        # primo strato che prende in input il numero di feature del dataset, il numero di neuroni, la funzione di attivazione ReLU
        Dense(10, activation='relu', input_dim=input_dim),      

        # strato di dropout, che disattiva casualmente un numero di neuroni durante ogni passaggio di addestramento per prevenire overfitting
        Dropout(0.2),                                           

        # strato che prende in input il numero di neuroni e la funzione di attivazione ReLU
        Dense(5, activation='relu'),

        # strato di dropout
        Dropout(0.2),

        # strato finale con un singolo neurone e una funzione di attivazione sigmoid
        Dense(num_classes, activation='softmax')  # Predice una singola feature
    ])

    # compilazione del modello in cui si specifica la funzione di perdita (MSE) e si utilizza come ottimizzatore Adam
    model.compile(loss='categorical_crossentropy', optimizer='adam')
    return model

In [166]:
def impute_feature_continua(dataset, feature):
    # Crea una copia del DataFrame
    dataset_copy = dataset.copy()
    
    # Divide i dati in feature e target
    X = dataset_copy.drop([feature], axis=1) # contiene tutte le colonne del DataFrame tranne la feature da imputare.
    y = dataset_copy[feature]                # contiene solo la colonna della feature da imputare

    # Identifica i valori mancanti nella feature da imputare
    missing_bool = y.isna()             # contiene valori booleani, true se il dato è mancante e false altrimenti
    
    # Separa i dati con e senza valori mancanti

    X_train = X[~missing_bool]                  # contiene le righe di X dove i valori non sono mancanti
    y_train = y[~missing_bool]                  # contiene le righe di y dove i valori non sono mancanti
    X_missing_values = X[missing_bool]          # contiene le righe di X dove i valori in y sono mancanti 
    
    # Costruzione e addestramento del modello
    model = build_model_linear(X_train.shape[1], 1)       # gli passo in input il numero di feature di X_train, in questo caso 23 -> 24 - feature da imputare
    model.fit(X_train, y_train, epochs=100, validation_split=0.2, verbose=0)    # si allena il modello su X_train e y_train per 100 epoche
    
    # Predizione dei valori mancanti
    y_pred = model.predict(X_missing_values)    # il modello addestrato viene utilizzato per predire i valori mancanti di y usando X_missing
    
    # Imputazione dei valori mancanti    
    y.loc[missing_bool] = y_pred.flatten()

    return y

In [167]:
import numpy as np

def impute_feature_discreta(dataset, feature):
    # Crea una copia del DataFrame
    dataset_copy = dataset.copy()
    
    # Divide i dati in feature e target
    X = dataset_copy.drop([feature], axis=1) # contiene tutte le colonne del DataFrame tranne la feature da imputare.
    y = dataset_copy[feature]                # contiene solo la colonna della feature da imputare

    # Identifica i valori mancanti nella feature da imputare
    missing_bool = y.isna()             # contiene valori booleani, true se il dato è mancante e false altrimenti
    
    # Separa i dati con e senza valori mancanti

    X_train = X[~missing_bool]                  # contiene le righe di X dove i valori non sono mancanti
    y_train = y[~missing_bool]                  # contiene le righe di y dove i valori non sono mancanti
    X_missing_values = X[missing_bool]          # contiene le righe di X dove i valori in y sono mancanti 
    
    # Costruzione e addestramento del modello
    model = build_model_sigmoid(X_train.shape[1], 1)       # gli passo in input il numero di feature di X_train, in questo caso 23 -> 24 - feature da imputare
    model.fit(X_train, y_train, epochs=100, validation_split=0.2, verbose=0)    # si allena il modello su X_train e y_train per 100 epoche
    
    # Predizione dei valori mancanti
    y_pred = model.predict(X_missing_values)    # il modello addestrato viene utilizzato per predire i valori mancanti di y usando X_missing
    y_pred = np.argmax(y_pred, axis=1)

    # Imputazione dei valori mancanti    
    y.loc[missing_bool] = y_pred.flatten()

    return y

In [168]:
dataset['ALO'] = impute_feature_continua(dataset, 'ALO')

/home/biso/anaconda3/lib/python3.11/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step

/tmp/ipykernel_1169/755403853.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y.loc[missing_bool] = y_pred.flatten()

In [169]:
dataset.isna().sum()

CASE_ID                     0
BREED                       0
GENDER_01                   0
AGEATSURGERYmo              0
BODYWEIGHTKG                0
Taglia                      0
BCS                         2
INDICATIONFORTHR            0
HIPRL                       1
YEAR                        0
n_luxation                  0
GENERATION                  0
STEMSIZE                    0
CUPSIZE                     0
NECKSIZE                    0
HEADSIZE                    0
ALO                         0
CUPRETROVERSION             0
STEMANTEVERSIONREAL         1
RECTUSFEMORISM.RELEASE      0
first_lux_days_after_thr    0
DIRECTION                   0
LUX_01                      0
LUX_CR                      0
dtype: int64

In [170]:
dataset['STEMANTEVERSIONREAL'] = impute_feature_continua(dataset, 'STEMANTEVERSIONREAL')

/home/biso/anaconda3/lib/python3.11/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step

/tmp/ipykernel_1169/755403853.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y.loc[missing_bool] = y_pred.flatten()

In [171]:
dataset.isna().sum()

CASE_ID                     0
BREED                       0
GENDER_01                   0
AGEATSURGERYmo              0
BODYWEIGHTKG                0
Taglia                      0
BCS                         2
INDICATIONFORTHR            0
HIPRL                       1
YEAR                        0
n_luxation                  0
GENERATION                  0
STEMSIZE                    0
CUPSIZE                     0
NECKSIZE                    0
HEADSIZE                    0
ALO                         0
CUPRETROVERSION             0
STEMANTEVERSIONREAL         0
RECTUSFEMORISM.RELEASE      0
first_lux_days_after_thr    0
DIRECTION                   0
LUX_01                      0
LUX_CR                      0
dtype: int64

In [172]:
dataset['BCS'] = impute_feature_continua(dataset, 'BCS')

/home/biso/anaconda3/lib/python3.11/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step

/tmp/ipykernel_1169/755403853.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y.loc[missing_bool] = y_pred.flatten()

In [173]:
dataset.isna().sum()

CASE_ID                     0
BREED                       0
GENDER_01                   0
AGEATSURGERYmo              0
BODYWEIGHTKG                0
Taglia                      0
BCS                         0
INDICATIONFORTHR            0
HIPRL                       1
YEAR                        0
n_luxation                  0
GENERATION                  0
STEMSIZE                    0
CUPSIZE                     0
NECKSIZE                    0
HEADSIZE                    0
ALO                         0
CUPRETROVERSION             0
STEMANTEVERSIONREAL         0
RECTUSFEMORISM.RELEASE      0
first_lux_days_after_thr    0
DIRECTION                   0
LUX_01                      0
LUX_CR                      0
dtype: int64

In [174]:
dataset['HIPRL'].mean()

0.5015644555694618

In [175]:
dataset['HIPRL'] = impute_feature_discreta(dataset, 'HIPRL')

/home/biso/anaconda3/lib/python3.11/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/home/biso/anaconda3/lib/python3.11/site-packages/keras/src/ops/nn.py:545: UserWarning: You are using a softmax over axis -1 of a tensor of shape (None, 1). This axis has size 1. The softmax operation will always return the value 1, which is likely not what you intended. Did you mean to use a sigmoid instead?
  warnings.warn(
/home/biso/anaconda3/lib/python3.11/site-packages/keras/src/losses/losses.py:22: SyntaxWarning: In loss categorical_crossentropy, expected y_pred.shape to be (batch_size, num_classes) with num_classes > 1. Received: y_pred.shape=(None, 1). Consider using 'binary_crossentropy' if you only have 2 classes.
  return self.fn(y_true, y_pred, **self._fn_kwargs)
/home/biso/anaconda3/lib/python3.11/site-packages/keras/src/ops/nn.py:545: UserWarning: You are using a softmax over axis -1 of a tensor of shape (32, 1). This axis has size 1. The softmax operation will always return the value 1, which is likely not what you intended. Did you mean to use a sigmoid instead?
  warnings.warn(
/home/biso/anaconda3/lib/python3.11/site-packages/keras/src/losses/losses.py:22: SyntaxWarning: In loss categorical_crossentropy, expected y_pred.shape to be (batch_size, num_classes) with num_classes > 1. Received: y_pred.shape=(32, 1). Consider using 'binary_crossentropy' if you only have 2 classes.
  return self.fn(y_true, y_pred, **self._fn_kwargs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step

/home/biso/anaconda3/lib/python3.11/site-packages/keras/src/ops/nn.py:545: UserWarning: You are using a softmax over axis -1 of a tensor of shape (1, 1). This axis has size 1. The softmax operation will always return the value 1, which is likely not what you intended. Did you mean to use a sigmoid instead?
  warnings.warn(
/tmp/ipykernel_1169/957488002.py:29: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  y.loc[missing_bool] = y_pred.flatten()

In [176]:
dataset.isna().sum()

CASE_ID                     0
BREED                       0
GENDER_01                   0
AGEATSURGERYmo              0
BODYWEIGHTKG                0
Taglia                      0
BCS                         0
INDICATIONFORTHR            0
HIPRL                       0
YEAR                        0
n_luxation                  0
GENERATION                  0
STEMSIZE                    0
CUPSIZE                     0
NECKSIZE                    0
HEADSIZE                    0
ALO                         0
CUPRETROVERSION             0
STEMANTEVERSIONREAL         0
RECTUSFEMORISM.RELEASE      0
first_lux_days_after_thr    0
DIRECTION                   0
LUX_01                      0
LUX_CR                      0
dtype: int64

In [177]:
dataset['HIPRL'].mean()

0.5014075695964967