### Imputation con regressione lineare e logistica (subdataset)

In [2]:
import pandas as pd
import imputation as imp 
import models

dataset = pd.read_csv('/home/biso/Tirocinio/tirocinio/Imputation/datiLussazioniDefinitivi.csv', delimiter=';')
dataset

,CASE_ID,BREED,GENDER_01,AGEATSURGERYmo,BODYWEIGHTKG,Taglia,BCS,INDICATIONFORTHR,HIPRL,YEAR,...,NECKSIZE,HEADSIZE,ALO,CUPRETROVERSION,STEMANTEVERSIONREAL,RECTUSFEMORISM.RELEASE,first_lux_days_after_thr,DIRECTION,LUX_01,LUX_CR
0,1,3,0,"56,5","31,6",1,5,4,R,2021,...,4,1,46.0,15,"17,7",NO,NaN,NaN,0,0
1,2,8,0,"9,4","40,9",1,5,4,L,2021,...,5,1,40.0,25,"27,7",NO,NaN,NaN,0,0
2,3,10,0,"15,1333333333333",35,1,5,4,R,2021,...,4,1,42.0,20,"27,7",YES,NaN,NaN,0,0
3,4,6,0,"83,4333333333333","18,7",0,6,4,L,2021,...,4,0,40.0,18,"24,2",NO,NaN,NaN,0,0
4,5,5,0,"7,53333333333333","36,4",1,4,4,L,2021,...,5,1,42.0,28,"25,9",YES,NaN,NaN,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3192,3193,3,0,"57,4333333333333",25,1,5,2,R,2010,...,3,0,43.0,32,"27,7",NO,35.0,CRANIO-DORSALE,1,1
3193,3194,5,1,"49,2333333333333",38,1,6,2,R,2009,...,4,0,48.0,26,"25,9",NO,18.0,CRANIO-DORSALE,1,1
3194,3195,13,0,"38,0333333333333",43,1,5,2,R,2008,...,4,0,48.0,4,"11,5",NO,30.0,CRANIO-DORSALE,1,1
3195,3196,5,1,"11,5333333333333",28,1,5,2,R,2001,...,4,0,52.0,10,"31,3",NO,26.0,CRANIO-DORSALE,1,1
3196,3197,3,0,"9,53",36,1,5,2,L,2020,...,4,1,43.0,35,"17,7",NO,83.0,CRANIO-DORSALE,1,1

In [3]:
dataset = imp.sub_dataset_cani(dataset)
dataset = imp.clean_dataset(dataset)

In [4]:
dataset

,CASE_ID,BREED,GENDER_01,AGEATSURGERYmo,BODYWEIGHTKG,Taglia,BCS,INDICATIONFORTHR,HIPRL,YEAR,...,NECKSIZE,HEADSIZE,ALO,CUPRETROVERSION,STEMANTEVERSIONREAL,RECTUSFEMORISM.RELEASE,first_lux_days_after_thr,DIRECTION,LUX_01,LUX_CR
0,3057,12,0,8.830000,30.0,1,6.0,4,0.0,2019,...,4,0,43.0,16,20.8,0,43.0,CAUDO-VENTRALE,1,0
1,3058,11,0,14.000000,24.8,1,4.0,4,0.0,2021,...,4,0,38.0,20,22.5,0,9.0,CAUDO-VENTRALE,1,0
2,3059,9,1,11.100000,32.2,1,5.0,4,1.0,2021,...,4,1,45.0,15,22.5,0,79.0,CAUDO-VENTRALE,1,0
3,3060,3,1,10.000000,31.8,1,5.0,4,1.0,2021,...,4,1,40.0,16,24.2,0,32.0,CRANIO-DORSALE,1,0
4,3061,3,1,7.770000,25.5,1,4.0,4,0.0,2018,...,4,1,45.0,8,20.8,0,222.0,CRANIO-DORSALE,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
418,2511,6,0,42.866667,28.2,1,8.0,2,1.0,2021,...,4,0,50.0,15,19.2,2,NaN,NaN,0,1
419,1328,10,0,12.566667,33.5,1,6.0,1,1.0,2012,...,5,0,37.0,16,27.7,0,NaN,NaN,0,0
420,678,10,0,8.466667,31.0,1,6.0,4,1.0,2018,...,4,0,43.0,18,17.7,0,NaN,NaN,0,0
421,2225,5,1,36.633333,27.0,1,5.0,4,1.0,1998,...,7,1,40.0,16,35.3,0,NaN,NaN,0,0
422,509,11,1,29.866667,21.2,1,5.0,4,0.0,2019,...,4,0,40.0,16,22.5,0,NaN,NaN,0,0

In [5]:
dataset.isna().sum()

CASE_ID                       0
BREED                         0
GENDER_01                     0
AGEATSURGERYmo                0
BODYWEIGHTKG                  0
Taglia                        0
BCS                           2
INDICATIONFORTHR              0
HIPRL                         1
YEAR                          0
n_luxation                  282
GENERATION                    0
STEMSIZE                      0
CUPSIZE                       0
NECKSIZE                      0
HEADSIZE                      0
ALO                           1
CUPRETROVERSION               0
STEMANTEVERSIONREAL           1
RECTUSFEMORISM.RELEASE        0
first_lux_days_after_thr    282
DIRECTION                   282
LUX_01                        0
LUX_CR                        0
dtype: int64

In [6]:
cols = ['n_luxation', 'first_lux_days_after_thr', 'DIRECTION']
dataset[cols] = dataset[cols].fillna(-1)

dataset['DIRECTION'] = dataset['DIRECTION'].replace('CRANIO-DORSALE', 0)
dataset['DIRECTION'] = dataset['DIRECTION'].replace('CAUDO-VENTRALE', 1)

In [7]:
# faccio imputation con regressione lineare e logistica
dataset = imp.total_imputation_regression(dataset)

/home/biso/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [8]:
dataset.isna().sum()

CASE_ID                     0
BREED                       0
GENDER_01                   0
AGEATSURGERYmo              0
BODYWEIGHTKG                0
Taglia                      0
BCS                         0
INDICATIONFORTHR            0
HIPRL                       0
YEAR                        0
n_luxation                  0
GENERATION                  0
STEMSIZE                    0
CUPSIZE                     0
NECKSIZE                    0
HEADSIZE                    0
ALO                         0
CUPRETROVERSION             0
STEMANTEVERSIONREAL         0
RECTUSFEMORISM.RELEASE      0
first_lux_days_after_thr    0
DIRECTION                   0
LUX_01                      0
LUX_CR                      0
dtype: int64

In [9]:
dataset.head()

,CASE_ID,BREED,GENDER_01,AGEATSURGERYmo,BODYWEIGHTKG,Taglia,BCS,INDICATIONFORTHR,HIPRL,YEAR,...,NECKSIZE,HEADSIZE,ALO,CUPRETROVERSION,STEMANTEVERSIONREAL,RECTUSFEMORISM.RELEASE,first_lux_days_after_thr,DIRECTION,LUX_01,LUX_CR
0,3057,12,0,8.83,30.0,1,6.0,4,0.0,2019,...,4,0,43.0,16,20.8,0,43.0,1,1,0
1,3058,11,0,14.00,24.8,1,4.0,4,0.0,2021,...,4,0,38.0,20,22.5,0,9.0,1,1,0
2,3059,9,1,11.10,32.2,1,5.0,4,1.0,2021,...,4,1,45.0,15,22.5,0,79.0,1,1,0
3,3060,3,1,10.00,31.8,1,5.0,4,1.0,2021,...,4,1,40.0,16,24.2,0,32.0,0,1,0
4,3061,3,1,7.77,25.5,1,4.0,4,0.0,2018,...,4,1,45.0,8,20.8,0,222.0,0,1,0

In [10]:
dataset = imp.drop_cols(dataset)

In [11]:
dataset = dataset.sample(frac=1, random_state=42)

In [12]:
feature_cols = ['BREED', 'GENDER_01', 'AGEATSURGERYmo', 'BODYWEIGHTKG', 'Taglia', 'BCS', 'INDICATIONFORTHR', 'HIPRL', 
                'YEAR', 'GENERATION', 'STEMSIZE', 'CUPSIZE', 'NECKSIZE', 'HEADSIZE', 'ALO', 'CUPRETROVERSION', 'STEMANTEVERSIONREAL', 
                'RECTUSFEMORISM.RELEASE', 'LUX_CR']

In [13]:
X = dataset[feature_cols]
y = dataset['LUX_01']

### Regressione logistica sulla feature LUX_01

In [14]:
model = models.logistic_regression_model(X, y)

Report di classificazione:
              precision    recall  f1-score   support

           0       0.75      0.87      0.80        83
           1       0.65      0.45      0.53        44

    accuracy                           0.72       127
   macro avg       0.70      0.66      0.67       127
weighted avg       0.71      0.72      0.71       127

### Regressione logistica con cross validation

In [15]:
model = models.logistic_regression_cv_model(X, y, cv=5)

Report di classificazione:
              precision    recall  f1-score   support

           0       0.79      0.92      0.85        83
           1       0.77      0.55      0.64        44

    accuracy                           0.79       127
   macro avg       0.78      0.73      0.74       127
weighted avg       0.79      0.79      0.78       127

### Regressione logistica con grid search cv

In [16]:
param_grid = {
    'C': [0.01, 0.1, 1]
}

model = models.logistic_regression_gridsearchcv_model(X=X,
                                                      y=y,
                                                      param_grid=param_grid,
                                                      cv=5,
                                                      scoring='accuracy')

Report di classificazione:
              precision    recall  f1-score   support

           0       0.79      0.90      0.84        83
           1       0.75      0.55      0.63        44

    accuracy                           0.78       127
   macro avg       0.77      0.72      0.74       127
weighted avg       0.78      0.78      0.77       127

Migliori parametri: {'C': 0.1}

### Albero di decisione

In [17]:
model = models.decision_tree_model(X=X,
                                   y=y,
                                   max_depth=15)

Report di classificazione:
              precision    recall  f1-score   support

           0       0.75      0.77      0.76        83
           1       0.55      0.52      0.53        44

    accuracy                           0.69       127
   macro avg       0.65      0.65      0.65       127
weighted avg       0.68      0.69      0.68       127

### Albero di decisione con grid search cv

In [18]:
param_grid = {
    'max_depth': [5, 10, 15]
}

model = models.decision_tree_gridsearchcv_model(X=X,
                                                y=y,
                                                param_grid=param_grid,
                                                cv=10,
                                                scoring='accuracy')

Report di classificazione:
              precision    recall  f1-score   support

           0       0.76      0.76      0.76        83
           1       0.55      0.55      0.55        44

    accuracy                           0.69       127
   macro avg       0.65      0.65      0.65       127
weighted avg       0.69      0.69      0.69       127

Migliori parametri: {'max_depth': 5}

### Random forest

In [19]:
model = models.random_forest_model(X=X,
                                   y=y,
                                   n_estimators=10,
                                   max_depth=10)

Report di classificazione:
              precision    recall  f1-score   support

           0       0.72      0.90      0.80        83
           1       0.65      0.34      0.45        44

    accuracy                           0.71       127
   macro avg       0.69      0.62      0.62       127
weighted avg       0.70      0.71      0.68       127

### Random forest con grid search cv

In [20]:
param_grid = {
    'max_depth': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
    'n_estimators': [7, 9, 11, 13]
}

model = models.random_forest_gridsearchcv_model(X=X,
                                                y=y,
                                                param_grid=param_grid,
                                                cv=10,
                                                scoring='accuracy')

Report di classificazione:
              precision    recall  f1-score   support

           0       0.72      0.92      0.81        83
           1       0.68      0.34      0.45        44

    accuracy                           0.72       127
   macro avg       0.70      0.63      0.63       127
weighted avg       0.71      0.72      0.69       127

Migliori parametri: {'max_depth': 4, 'n_estimators': 9}