### Imputation con rete neurale (una feature alla volta)

In [35]:
import pandas as pd
import imputation as imp 
import models 

dataset = pd.read_csv('/home/biso/tirocinio/Imputation/datiLussazioniDefinitivi.csv', delimiter=';')
dataset

,CASE_ID,BREED,GENDER_01,AGEATSURGERYmo,BODYWEIGHTKG,Taglia,BCS,INDICATIONFORTHR,HIPRL,YEAR,...,NECKSIZE,HEADSIZE,ALO,CUPRETROVERSION,STEMANTEVERSIONREAL,RECTUSFEMORISM.RELEASE,first_lux_days_after_thr,DIRECTION,LUX_01,LUX_CR
0,1,3,0,"56,5","31,6",1,5,4,R,2021,...,4,1,46.0,15,"17,7",NO,NaN,NaN,0,0
1,2,8,0,"9,4","40,9",1,5,4,L,2021,...,5,1,40.0,25,"27,7",NO,NaN,NaN,0,0
2,3,10,0,"15,1333333333333",35,1,5,4,R,2021,...,4,1,42.0,20,"27,7",YES,NaN,NaN,0,0
3,4,6,0,"83,4333333333333","18,7",0,6,4,L,2021,...,4,0,40.0,18,"24,2",NO,NaN,NaN,0,0
4,5,5,0,"7,53333333333333","36,4",1,4,4,L,2021,...,5,1,42.0,28,"25,9",YES,NaN,NaN,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3192,3193,3,0,"57,4333333333333",25,1,5,2,R,2010,...,3,0,43.0,32,"27,7",NO,35.0,CRANIO-DORSALE,1,1
3193,3194,5,1,"49,2333333333333",38,1,6,2,R,2009,...,4,0,48.0,26,"25,9",NO,18.0,CRANIO-DORSALE,1,1
3194,3195,13,0,"38,0333333333333",43,1,5,2,R,2008,...,4,0,48.0,4,"11,5",NO,30.0,CRANIO-DORSALE,1,1
3195,3196,5,1,"11,5333333333333",28,1,5,2,R,2001,...,4,0,52.0,10,"31,3",NO,26.0,CRANIO-DORSALE,1,1
3196,3197,3,0,"9,53",36,1,5,2,L,2020,...,4,1,43.0,35,"17,7",NO,83.0,CRANIO-DORSALE,1,1

In [36]:
dataset = imp.clean_dataset(dataset)

dataset['DIRECTION'] = dataset['DIRECTION'].replace('CRANIO-DORSALE', 0)
dataset['DIRECTION'] = dataset['DIRECTION'].replace('CAUDO-VENTRALE', 1)

cols = ['n_luxation', 'first_lux_days_after_thr', 'DIRECTION']
dataset[cols] = dataset[cols].fillna(-1)

In [37]:
dataset.isna().sum()

CASE_ID                     0
BREED                       0
GENDER_01                   0
AGEATSURGERYmo              0
BODYWEIGHTKG                0
Taglia                      0
BCS                         2
INDICATIONFORTHR            0
HIPRL                       1
YEAR                        0
n_luxation                  0
GENERATION                  0
STEMSIZE                    0
CUPSIZE                     0
NECKSIZE                    0
HEADSIZE                    0
ALO                         1
CUPRETROVERSION             0
STEMANTEVERSIONREAL         1
RECTUSFEMORISM.RELEASE      0
first_lux_days_after_thr    0
DIRECTION                   0
LUX_01                      0
LUX_CR                      0
dtype: int64

In [38]:
dataset.head()

,CASE_ID,BREED,GENDER_01,AGEATSURGERYmo,BODYWEIGHTKG,Taglia,BCS,INDICATIONFORTHR,HIPRL,YEAR,...,NECKSIZE,HEADSIZE,ALO,CUPRETROVERSION,STEMANTEVERSIONREAL,RECTUSFEMORISM.RELEASE,first_lux_days_after_thr,DIRECTION,LUX_01,LUX_CR
0,1,3,0,56.500000,31.6,1,5.0,4,1.0,2021,...,4,1,46.0,15,17.7,0,-1.0,-1.0,0,0
1,2,8,0,9.400000,40.9,1,5.0,4,0.0,2021,...,5,1,40.0,25,27.7,0,-1.0,-1.0,0,0
2,3,10,0,15.133333,35.0,1,5.0,4,1.0,2021,...,4,1,42.0,20,27.7,1,-1.0,-1.0,0,0
3,4,6,0,83.433333,18.7,0,6.0,4,0.0,2021,...,4,0,40.0,18,24.2,0,-1.0,-1.0,0,0
4,5,5,0,7.533333,36.4,1,4.0,4,0.0,2021,...,5,1,42.0,28,25.9,1,-1.0,-1.0,0,0

In [39]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
dataset = pd.DataFrame(scaler.fit_transform(dataset), columns=dataset.columns)

In [40]:
dataset

,CASE_ID,BREED,GENDER_01,AGEATSURGERYmo,BODYWEIGHTKG,Taglia,BCS,INDICATIONFORTHR,HIPRL,YEAR,...,NECKSIZE,HEADSIZE,ALO,CUPRETROVERSION,STEMANTEVERSIONREAL,RECTUSFEMORISM.RELEASE,first_lux_days_after_thr,DIRECTION,LUX_01,LUX_CR
0,-1.731509,-1.240739,-0.899601,0.500151,-0.071167,0.314648,-0.394244,0.548247,0.996876,1.217012,...,-0.320497,0.679800,0.757868,-0.489188,-1.122834,-0.461204,-0.072201,-0.203340,-0.214799,-0.504200
1,-1.730426,0.183140,-0.899601,-0.831594,0.894775,0.314648,-0.394244,0.548247,-1.003134,1.217012,...,1.160181,0.679800,-1.034986,1.187233,0.257261,-0.461204,-0.072201,-0.203340,-0.214799,-0.504200
2,-1.729342,0.752692,-0.899601,-0.669485,0.281973,0.314648,-0.394244,0.548247,0.996876,1.217012,...,-0.320497,0.679800,-0.437368,0.349023,0.257261,0.982938,-0.072201,-0.203340,-0.214799,-0.504200
3,-1.728258,-0.386412,-0.899601,1.261686,-1.411021,-3.178159,0.826308,0.548247,-1.003134,1.217012,...,-0.320497,-0.644588,-1.034986,0.013739,-0.225773,-0.461204,-0.072201,-0.203340,-0.214799,-0.504200
4,-1.727175,-0.671187,-0.899601,-0.884374,0.427384,0.314648,-1.614796,0.548247,-1.003134,1.217012,...,1.160181,0.679800,-0.437368,1.690160,0.008844,0.982938,-0.072201,-0.203340,-0.214799,-0.504200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3192,1.727175,-1.240739,-0.899601,0.526540,-0.756674,0.314648,-0.394244,-1.745922,0.996876,-0.748122,...,-1.801175,-0.644588,-0.138559,2.360728,0.257261,-0.461204,0.239095,3.643267,4.655508,1.983341
3193,1.728258,-0.671187,1.111604,0.294687,0.593567,0.314648,0.826308,-1.745922,0.996876,-0.926771,...,-0.320497,-0.644588,1.355485,1.354876,0.008844,-0.461204,0.092094,3.643267,4.655508,1.983341
3194,1.729342,1.607020,-0.899601,-0.021991,1.112890,0.314648,-0.394244,-1.745922,0.996876,-1.105419,...,-0.320497,-0.644588,1.355485,-2.333251,-1.978493,-0.461204,0.195860,3.643267,4.655508,1.983341
3195,1.730426,-0.671187,1.111604,-0.771274,-0.445080,0.314648,-0.394244,-1.745922,0.996876,-2.355959,...,-0.320497,-0.644588,2.550721,-1.327398,0.754095,-0.461204,0.161271,3.643267,4.655508,1.983341
3196,1.731509,-1.240739,-0.899601,-0.827918,0.385838,0.314648,-0.394244,-1.745922,-1.003134,1.038363,...,-0.320497,0.679800,-0.138559,2.863655,-1.122834,-0.461204,0.654157,3.643267,4.655508,1.983341

In [41]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import Adam


# Creazione del modello di rete neurale
def build_model(input_dim):
    model = Sequential([
        Dense(64, activation='relu', input_dim=input_dim),
        Dropout(0.2),
        Dense(32, activation='relu'),
        Dropout(0.2),
        Dense(1, activation='linear')  # Predice una singola feature
    ])
    model.compile(loss='mse', optimizer='adam')
    return model

In [42]:
def impute_feature(df, feature):
    # Crea una copia del DataFrame
    df_copy = df.copy()
    
    # Divide i dati in feature e target
    X = df_copy.drop(columns=[feature]) # contiene tutte le colonne del DataFrame tranne la feature da imputare.
    y = df_copy[feature]                # contiene solo la colonna della feature da imputare

    # Identifica i valori mancanti nella feature da imputare
    missing_bool = y.isna()             # contiene valori booleani, true se il dato è mancante e false altrimenti
    
    # Separa i dati con e senza valori mancanti

    X_train = X[~missing_bool]          # contiene le righe di X dove i valori non sono mancanti
    y_train = y[~missing_bool]          # contiene le righe di y dove i valori non sono mancanti
    X_missing = X[missing_bool]         # contiene le righe di X dove i valori in y sono mancanti 
    
    # Costruzione e addestramento del modello
    model = build_model(X_train.shape[1])
    model.fit(X_train, y_train, epochs=100, batch_size=8, validation_split=0.2, verbose=0)
    
    # Predizione dei valori mancanti
    y_pred = model.predict(X_missing)
    
    # Imputazione dei valori mancanti
    y.loc[missing_bool] = y_pred.flatten()
    
    return y

In [43]:
dataset['ALO'] =impute_feature(dataset, 'ALO')

       CASE_ID     BREED  GENDER_01  AGEATSURGERYmo  BODYWEIGHTKG    Taglia  \
2327  0.789906 -1.240739  -0.899601       -0.677025      3.917237  0.314648

           BCS  INDICATIONFORTHR     HIPRL      YEAR  ...   CUPSIZE  NECKSIZE  \
2327 -0.394244          0.548247 -1.003134  0.681066  ...  3.597708   8.56357

      HEADSIZE  CUPRETROVERSION  STEMANTEVERSIONREAL  RECTUSFEMORISM.RELEASE  \
2327  4.652967          1.69016             0.008844               -0.461204

      first_lux_days_after_thr  DIRECTION    LUX_01  LUX_CR
2327                 -0.072201   -0.20334 -0.214799 -0.5042

[1 rows x 23 columns]

/home/biso/anaconda3/lib/python3.11/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step

In [44]:
dataset.isna().sum()

CASE_ID                     0
BREED                       0
GENDER_01                   0
AGEATSURGERYmo              0
BODYWEIGHTKG                0
Taglia                      0
BCS                         2
INDICATIONFORTHR            0
HIPRL                       1
YEAR                        0
n_luxation                  0
GENERATION                  0
STEMSIZE                    0
CUPSIZE                     0
NECKSIZE                    0
HEADSIZE                    0
ALO                         0
CUPRETROVERSION             0
STEMANTEVERSIONREAL         1
RECTUSFEMORISM.RELEASE      0
first_lux_days_after_thr    0
DIRECTION                   0
LUX_01                      0
LUX_CR                      0
dtype: int64