In [30]:
import pandas as pd

In [31]:
dataset = pd.read_csv('../csv/dataset_original.csv')
dataset

,BREED,GENDER_01,AGEATSURGERYmo,BODYWEIGHTKG,Taglia,BCS,YEAR,n_luxation,GENERATION,STEMSIZE,...,NECKSIZE,HEADSIZE,ALO,CUPRETROVERSION,STEMANTEVERSIONREAL,RECTUSFEMORISM.RELEASE,first_lux_days_after_thr,DIRECTION,LUX_01,LUX_CR
0,3,0,56.500000,31.6,1,5.0,2021,-1.0,6,0,...,4,1,46.0,15,17.7,0,-1.0,-1.0,0,0
1,8,0,9.400000,40.9,1,5.0,2021,-1.0,6,1,...,5,1,40.0,25,27.7,0,-1.0,-1.0,0,0
2,10,0,15.133333,35.0,1,5.0,2021,-1.0,6,0,...,4,1,42.0,20,27.7,1,-1.0,-1.0,0,0
3,6,0,83.433333,18.7,0,6.0,2021,-1.0,6,2,...,4,0,40.0,18,24.2,0,-1.0,-1.0,0,0
4,5,0,7.533333,36.4,1,4.0,2021,-1.0,6,1,...,5,1,42.0,28,25.9,1,-1.0,-1.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3192,3,0,57.433333,25.0,1,5.0,2010,1.0,4,3,...,3,0,43.0,32,27.7,0,35.0,0.0,1,1
3193,5,1,49.233333,38.0,1,6.0,2009,1.0,4,0,...,4,0,48.0,26,25.9,0,18.0,0.0,1,1
3194,13,0,38.033333,43.0,1,5.0,2008,2.0,3,1,...,4,0,48.0,4,11.5,0,30.0,0.0,1,1
3195,5,1,11.533333,28.0,1,5.0,2001,1.0,2,0,...,4,0,52.0,10,31.3,0,26.0,0.0,1,1
3196,3,0,9.530000,36.0,1,5.0,2020,2.0,6,3,...,4,1,43.0,35,17.7,0,83.0,0.0,1,1

In [32]:
dataset.dtypes

BREED                         int64
GENDER_01                     int64
AGEATSURGERYmo              float64
BODYWEIGHTKG                float64
Taglia                        int64
BCS                         float64
YEAR                          int64
n_luxation                  float64
GENERATION                    int64
STEMSIZE                      int64
CUPSIZE                       int64
NECKSIZE                      int64
HEADSIZE                      int64
ALO                         float64
CUPRETROVERSION               int64
STEMANTEVERSIONREAL         float64
RECTUSFEMORISM.RELEASE        int64
first_lux_days_after_thr    float64
DIRECTION                   float64
LUX_01                        int64
LUX_CR                        int64
dtype: object

In [33]:
nonum_feats_names = ['BREED', 'GENDER_01', 'Taglia', 'YEAR', 'GENERATION', 'STEMSIZE', 'CUPSIZE', 'NECKSIZE', 'HEADSIZE', 'CUPRETROVERSION', 'RECTUSFEMORISM.RELEASE', 'LUX_01', 'LUX_CR']
num_cols_names = ['AGEATSURGERYmo', 'BODYWEIGHTKG', 'BCS', 'ALO', 'STEMANTEVERSIONREAL']

In [34]:
#Assign appropriate data type to categorical variables.
nonum_feats = dataset[nonum_feats_names].astype('category')
nonum_feats.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3197 entries, 0 to 3196
Data columns (total 13 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   BREED                   3197 non-null   category
 1   GENDER_01               3197 non-null   category
 2   Taglia                  3197 non-null   category
 3   YEAR                    3197 non-null   category
 4   GENERATION              3197 non-null   category
 5   STEMSIZE                3197 non-null   category
 6   CUPSIZE                 3197 non-null   category
 7   NECKSIZE                3197 non-null   category
 8   HEADSIZE                3197 non-null   category
 9   CUPRETROVERSION         3197 non-null   category
 10  RECTUSFEMORISM.RELEASE  3197 non-null   category
 11  LUX_01                  3197 non-null   category
 12  LUX_CR                  3197 non-null   category
dtypes: category(13)
memory usage: 45.8 KB

In [35]:
ohc_feats = pd.get_dummies(nonum_feats,drop_first=True)
ohc_feats.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3197 entries, 0 to 3196
Columns: 120 entries, BREED_2 to LUX_CR_1
dtypes: bool(120)
memory usage: 374.8 KB

In [36]:
ohc_feats

,BREED_2,BREED_3,BREED_4,BREED_5,BREED_6,BREED_7,BREED_8,BREED_9,BREED_10,BREED_11,...,CUPRETROVERSION_34,CUPRETROVERSION_35,CUPRETROVERSION_36,CUPRETROVERSION_37,CUPRETROVERSION_38,CUPRETROVERSION_40,RECTUSFEMORISM.RELEASE_1,RECTUSFEMORISM.RELEASE_2,LUX_01_1,LUX_CR_1
0,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,True,False,False,False
3,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3192,False,True,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
3193,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
3194,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
3195,False,False,False,True,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,True
3196,False,True,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,True,True

In [37]:
ohc_data = pd.concat([dataset[num_cols_names], ohc_feats.drop('LUX_01_1', axis=1)],axis=1)
ohc_data

,AGEATSURGERYmo,BODYWEIGHTKG,BCS,ALO,STEMANTEVERSIONREAL,BREED_2,BREED_3,BREED_4,BREED_5,BREED_6,...,CUPRETROVERSION_33,CUPRETROVERSION_34,CUPRETROVERSION_35,CUPRETROVERSION_36,CUPRETROVERSION_37,CUPRETROVERSION_38,CUPRETROVERSION_40,RECTUSFEMORISM.RELEASE_1,RECTUSFEMORISM.RELEASE_2,LUX_CR_1
0,56.500000,31.6,5.0,46.0,17.7,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,9.400000,40.9,5.0,40.0,27.7,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,15.133333,35.0,5.0,42.0,27.7,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
3,83.433333,18.7,6.0,40.0,24.2,False,False,False,False,True,...,False,False,False,False,False,False,False,False,False,False
4,7.533333,36.4,4.0,42.0,25.9,False,False,False,True,False,...,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3192,57.433333,25.0,5.0,43.0,27.7,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,True
3193,49.233333,38.0,6.0,48.0,25.9,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,True
3194,38.033333,43.0,5.0,48.0,11.5,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
3195,11.533333,28.0,5.0,52.0,31.3,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,True
3196,9.530000,36.0,5.0,43.0,17.7,False,True,False,False,False,...,False,False,True,False,False,False,False,False,False,True

In [38]:
target = ohc_feats['LUX_01_1']

In [39]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score, roc_auc_score, recall_score, precision_score, classification_report
from imblearn.over_sampling import SMOTENC
from sklearn.preprocessing import StandardScaler

In [40]:
def baseline_models(data=[], verbose=False):
    #List of models to be used
    models=[DecisionTreeClassifier(),LogisticRegression(),
            RandomForestClassifier(),GradientBoostingClassifier()]
    #Create training and testing data sets depending on wheather or not they have been generated previously.
    if len(data)== 2:
        X_train, X_test, y_train, y_test = train_test_split(data[0],data[1],random_state=123)
    else:
        X_train, X_test, y_train, y_test = data[0],data[1],data[2],data[3]
    #Instantiate lists to store each of the models results
    accuracy = []
    f1 = []
    auc = []
    recall = []
    precision = []
    #Run thorugh each of the models to get their performance metrics
    for model in models:
        clf = model
        clf.fit(X_train, y_train)
        test_preds = clf.predict(X_test)
        f1.append(f1_score(y_test, test_preds))
        accuracy.append(accuracy_score(y_test, test_preds))
        auc.append(roc_auc_score(y_test, test_preds))
        recall.append(recall_score(y_test, test_preds))
        precision.append(precision_score(y_test, test_preds))
        #Print the model and its report
        if verbose:
            print('Classification Model: ',model,'\n')
            print(classification_report(y_test, test_preds),'\n')
    #store results in dataframe
    results = pd.DataFrame([f1,auc, accuracy, precision,recall],
                      index= ['f1','roc_auc','accuracy','precision','recall',],
                           columns=['DecisionTree','LogisticRegression','RandomForest','Gradient Boosting'])
    #Change orientation of the dataframe
    return results.transpose()

In [41]:
target.value_counts()

LUX_01_1
False    3056
True      141
Name: count, dtype: int64

In [48]:
#Create a final dataframe with all numerical variables in the first columns.
final_df = pd.concat([ohc_data[num_cols_names],ohc_feats.drop('LUX_01_1', axis=1)],axis=1)
#Create final train and test sets startified according to the target variable. 
X_train, X_test, y_train, y_test = train_test_split(final_df,target, test_size = 0.30,stratify=target, 
                                                    random_state=123)

In [49]:
'''Scaling the data first fitting it and transforming the training set
to later apply the fit to transform the test set.'''
#Instantiate Satandard Scaler
scaler = StandardScaler()
#Fit transform the numerical features in the training dataset to a new dataframe
scaled_numfeats_train = pd.DataFrame(scaler.fit_transform(X_train[num_cols_names]), 
                                     columns=num_cols_names, index= X_train.index)
#Integrate scaled values to the training set
for col in num_cols_names:
    X_train[col] = scaled_numfeats_train[col]
#Transform the numerical features inthe training dataset to a new dataframe
scaled_numfeats_test = pd.DataFrame(scaler.transform(X_test[num_cols_names]),
                                    columns=num_cols_names, index= X_test.index)
#Integrate scaled values to the test set
for col in num_cols_names:
    X_test[col] = scaled_numfeats_test[col]

In [50]:
#Display scores for each of the models
results3 = baseline_models(data=[X_train, X_test, y_train, y_test], verbose=True)
results3.sort_values('f1',ascending=False)

Classification Model:  DecisionTreeClassifier()

              precision    recall  f1-score   support

       False       0.96      0.96      0.96       918
        True       0.11      0.12      0.11        42

    accuracy                           0.92       960
   macro avg       0.54      0.54      0.54       960
weighted avg       0.92      0.92      0.92       960


Classification Model:  LogisticRegression()

              precision    recall  f1-score   support

       False       0.96      0.99      0.98       918
        True       0.17      0.02      0.04        42

    accuracy                           0.95       960
   macro avg       0.56      0.51      0.51       960
weighted avg       0.92      0.95      0.93       960


Classification Model:  RandomForestClassifier()

              precision    recall  f1-score   support

       False       0.96      1.00      0.98       918
        True       1.00      0.02      0.05        42

    accuracy                           0.96       960
   macro avg       0.98      0.51      0.51       960
weighted avg       0.96      0.96      0.94       960


Classification Model:  GradientBoostingClassifier()

              precision    recall  f1-score   support

       False       0.96      1.00      0.98       918
        True       0.67      0.05      0.09        42

    accuracy                           0.96       960
   macro avg       0.81      0.52      0.53       960
weighted avg       0.95      0.96      0.94       960

                          f1   roc_auc  accuracy  precision    recall
DecisionTree        0.114943  0.537737  0.919792   0.111111  0.119048
Gradient Boosting   0.088889  0.523265  0.957292   0.666667  0.047619
RandomForest        0.046512  0.511905  0.957292   1.000000  0.023810
LogisticRegression  0.041667  0.509181  0.952083   0.166667  0.023810

In [51]:
def get_strategy_oversampling(n_negativi, rapporto):
    """
    Calcola il numero di esempi positivi per il sovracampionamento.

    Args:
        n_negativi (int): Il numero di esempi negativi.
        rapporto (float): Il rapporto desiderato tra esempi positivi e negativi.

    Returns:
        n_positivi: Il numero di esempi positivi da generare.
    """
    n_positivi = (1 / rapporto * n_negativi) - n_negativi
    return int(n_positivi)

In [52]:
n_negative = len(dataset[dataset['LUX_01']==0])
n_positive = get_strategy_oversampling(n_negative, 2/3)

sampling_strategy = {0: n_negative, 1: n_positive}

In [53]:
#Obatin column index for categorical features
cat_col_index = list(range(len(num_cols_names),59))
#Instantiate SMOTENC algorith with 60% oversampling
sm = SMOTENC(categorical_features=cat_col_index, random_state=123, sampling_strategy=sampling_strategy)
X_trainres, y_trainres = sm.fit_resample(X_train, y_train)

In [54]:
y_trainres.value_counts()

LUX_01_1
False    3056
True     1528
Name: count, dtype: int64

In [55]:
results_final = baseline_models(data=[X_trainres, X_test, y_trainres, y_test], verbose=True)
results_final.sort_values('f1', ascending=False)

Classification Model:  DecisionTreeClassifier()

              precision    recall  f1-score   support

       False       0.96      0.93      0.95       918
        True       0.09      0.14      0.11        42

    accuracy                           0.90       960
   macro avg       0.53      0.54      0.53       960
weighted avg       0.92      0.90      0.91       960


Classification Model:  LogisticRegression()

              precision    recall  f1-score   support

       False       0.96      0.98      0.97       918
        True       0.11      0.05      0.07        42

    accuracy                           0.94       960
   macro avg       0.53      0.51      0.52       960
weighted avg       0.92      0.94      0.93       960

/home/biso/anaconda3/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Classification Model:  RandomForestClassifier()

              precision    recall  f1-score   support

       False       0.96      1.00      0.98       918
        True       0.40      0.05      0.09        42

    accuracy                           0.96       960
   macro avg       0.68      0.52      0.53       960
weighted avg       0.93      0.96      0.94       960


Classification Model:  GradientBoostingClassifier()

              precision    recall  f1-score   support

       False       0.96      0.98      0.97       918
        True       0.19      0.10      0.13        42

    accuracy                           0.94       960
   macro avg       0.58      0.54      0.55       960
weighted avg       0.93      0.94      0.93       960

                          f1   roc_auc  accuracy  precision    recall
Gradient Boosting   0.126984  0.538360  0.942708   0.190476  0.095238
DecisionTree        0.111111  0.538749  0.900000   0.090909  0.142857
RandomForest        0.085106  0.522176  0.955208   0.400000  0.047619
LogisticRegression  0.065574  0.514550  0.940625   0.105263  0.047619